#ifndef __SWITCH_H__
#define __SWITCH_H__ 1

#define SWITCH_COUNT 22

typedef enum
{
  SWITCH_MODE_S = 33,
  SWITCH_MODE_C = 34,
} SwitchMode;

typedef enum
{
  TRACK_A = 0,
  COUNT = 1,
} TrackSwitchPlans;

static const SwitchMode TRACK_PLANS[COUNT][SWITCH_COUNT] = {
    {SWITCH_MODE_S, SWITCH_MODE_S, SWITCH_MODE_S, SWITCH_MODE_S, SWITCH_MODE_C, SWITCH_MODE_S,
     SWITCH_MODE_S, SWITCH_MODE_C, SWITCH_MODE_C, SWITCH_MODE_S, SWITCH_MODE_C, SWITCH_MODE_C,
     SWITCH_MODE_S, SWITCH_MODE_C, SWITCH_MODE_C, SWITCH_MODE_S, SWITCH_MODE_S, SWITCH_MODE_C,
     SWITCH_MODE_S, SWITCH_MODE_C, SWITCH_MODE_S, SWITCH_MODE_C

    }};

#endif // __SWITCH_H__
